CCNetStore/Models/Order.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNetStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int clientId { get; set; }
        public System.DateTime orderDate { get; set; }
        public decimal totalPrice { get; set; }
        public string orderStatus { get; set; }
        public string deliveryAddress { get; set; }
    
        public virtual client client { get; set; }
    }
}

CCNetStore/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CCNetStore.Models;

namespace CCNetStore.Controllers
{
    public class CartsController : Controller
    {
        private CCStoreEntities db = new CCStoreEntities();

        public static decimal totalPrice = 0;
        // GET: Carts
        [Authorize(Roles ="admin, manager")]
        public ActionResult Index()
        {
            var carts = db.carts.Include(c => c.client).Include(c => c.product);
            return View(carts.Where(c => c.productStatus == "free").ToList());
        }
        [Authorize(Roles = "client")]
        public ActionResult IndexClient()
        {
            var carts = db.carts.Include(c => c.client).Include(c => c.product);
            if(carts.Where(c => c.client.clientLogin == User.Identity.Name).FirstOrDefault() != null && carts.Where(c => c.productStatus == "free").FirstOrDefault() != null)
            {
                totalPrice = carts.Where(c => c.client.clientLogin == User.Identity.Name).Sum(p => p.product.productPrice).Value;
            }
            return View(carts.Where(c => c.client.clientLogin == User.Identity.Name && c.productStatus == "free").ToList());
        }

        // GET: Carts/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cart cart = db.carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cart cart = db.carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cart cart = db.carts.Find(id);
            db.carts.Remove(cart);

            db.SaveChanges();
            if(User.IsInRole("admin") || User.IsInRole("manager"))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("IndexClient");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CCNetStore/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CCNetStore.Models;

namespace CCNetStore.Controllers
{
    public class ClientsController : Controller
    {
        private CCStoreEntities db = new CCStoreEntities();

        // GET: Clients
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View(db.clients.ToList());
        }

        // GET: Clients/Details/5
        [Authorize(Roles = "admin")]
        public ActionResult Details(int id)
        {
            client client = db.clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "clientId,clientLogin,clientPassword,clientRole")] client client)
        {
            if (ModelState.IsValid)
            {
                db.clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Clients/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            client client = db.clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "clientId,clientLogin,clientPassword,clientRole")] client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int id)
        {
            client client = db.clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            client client = db.clients.Find(id);
            db.clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CCNetStore/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CCNetStore.Models;

namespace CCNetStore.Controllers
{
    public class OrdersController : Controller
    {
        private CCStoreEntities db = new CCStoreEntities();

        // GET: PayForTheOrder
        [Authorize]
        public ActionResult PayForTheOrder(int id)
        {
            var order = db.Orders.Where(o => o.Id == id).FirstOrDefault();
            if (order.orderStatus == "confirmed")
            {
                order.orderStatus = "PAYED";
                int clientId = db.clients.FirstOrDefault(u => u.clientLogin == User.Identity.Name).clientId;
                var carts = db.carts.Where(c => c.clientId == clientId).ToList();

                db.carts.RemoveRange(carts);
                db.SaveChanges();
            }
            else
            {
                return RedirectToAction("IndexClient");
            }

            return View();
        }

        // GET: ConfirmOrder
        [Authorize]
        public ActionResult ConfirmOrder()
        {
            int clientId = db.clients.FirstOrDefault(c => c.clientLogin == User.Identity.Name).clientId;

            var carts = db.carts.Where(c => c.clientId == clientId).ToList();
            carts.ForEach(c => c.productStatus = "reservated");

            var listId = carts.Select(c => c.productId);

            var products = db.products.Where(p => listId.Contains(p.productId)).ToList();
            products.ForEach(p => p.productQuantity--);

            db.SaveChanges();

            db.Orders.Add(new Order { clientId = clientId, orderDate = DateTime.Now, totalPrice = CartsController.totalPrice, orderStatus = "confirmed", deliveryAddress = null});
            db.SaveChanges();
            CartsController.totalPrice = 0;
            return View();
        }

        // GET: Orders
        [Authorize(Roles = "admin, manager")]
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.client);
            return View(orders.ToList());
        }
        [Authorize]
        public ActionResult IndexClient()
        {
            var orders = db.Orders.Include(o => o.client);
            return View(orders.Where(c => c.client.clientLogin == User.Identity.Name).ToList());
        }

        // GET: Orders/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.clientId = new SelectList(db.clients, "clientId", "clientLogin", order.clientId);
            return View(order);
        }

        // POST: Orders/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,clientId,orderDate,totalPrice,orderStatus,deliveryAddress")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                if(User.IsInRole("admin") || User.IsInRole("manager"))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("IndexClient");
                }
            }
            ViewBag.clientId = new SelectList(db.clients, "clientId", "clientLogin", order.clientId);
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            
            int clientId = db.clients.FirstOrDefault(u => u.clientLogin == User.Identity.Name).clientId;
            var carts = db.carts.Where(c => c.clientId == clientId).ToList();

            if (order.orderStatus != "PAYED")
            {
                var listId = carts.Select(c => c.productId);
                var products = db.products.Where(p => listId.Contains(p.productId)).ToList();
                products.ForEach(p => p.productQuantity++);
            }

            db.carts.RemoveRange(carts);

            db.SaveChanges();
            if (User.IsInRole("admin") || User.IsInRole("manager"))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("IndexClient");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CCNetStore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CCNetStore.Models;

namespace CCNetStore.Controllers
{
    public class ProductsController : Controller
    {
        private CCStoreEntities db = new CCStoreEntities();

        // GET: AddToCart
        [Authorize(Roles = "client")]
        public ActionResult AddToCart(string id, string name)
        {
            int clientId = db.clients.FirstOrDefault(u => u.clientLogin == User.Identity.Name).clientId;

            var orders = db.carts.Where(c => c.clientId == clientId && c.productStatus == "reservated").FirstOrDefault();

            if (orders == null)
            {
                db.carts.Add(new cart { clientId = clientId, productId = id, productName = name, cpQuantity = 1, productStatus = "free" });
                db.SaveChanges();
            }
            else
            {
                return RedirectToAction("IndexClient");
            }

            return View();
        }

        // GET: Progucts
        [Authorize]
        public ActionResult IndexClient()
        {
            return View(db.products.ToList());
        }

        // GET: Products
        [Authorize(Roles = "admin, manager")]
        public ActionResult IndexManager()
        {
            return View(db.products.ToList());
        }

        // GET: Products/Details/5
        [Authorize]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles = "admin, manager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        [Authorize(Roles = "admin, manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "productId,productName,productQuantity,productDescription,productPrice,productStatus")] product product)
        {
            if (ModelState.IsValid)
            {
                db.products.Add(product);
                db.SaveChanges();
                return RedirectToAction("IndexManager");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "admin, manager")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        [Authorize(Roles = "admin, manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "productId,productName,productQuantity,productDescription,productPrice,productStatus")] product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexManager");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "admin, manager")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [Authorize(Roles = "admin, manager")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            product product = db.products.Find(id);
            db.products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("IndexManager");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CCNetStore/Views/Orders/ConfirmOrder.cshtml
@{
    ViewBag.Title = "ConfirmOrder";
}

<h2>Order confirmed</h2>

<div>
    <div class="col-md-offset-0 col-md-12">
        <h4>[@Html.ActionLink("Back to catlog", "IndexClient", "Products")] &nbsp; [@Html.ActionLink("To orders", "IndexClient")]</h4>
    </div>
</div>

CCNetStore/Views/Orders/Delete.cshtml
@model CCNetStore.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this order?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.orderDate)
        </dd>

        <dt>
            @Html.DisplayName("Total price")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalPrice)
        </dd>

        <dt>
            @Html.DisplayName("Order status")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.orderStatus)
        </dd>

        <dt>
            @Html.DisplayName("Login")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.client.clientLogin)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @if (User.IsInRole("admin") || User.IsInRole("manager"))
            {
                @Html.ActionLink("Back to List", "Index")
            }
            else
            {
                @Html.ActionLink("Back to List", "IndexClient")
            }
        </div>
    }
</div>

CCNetStore/Views/Orders/Details.cshtml
@model CCNetStore.Models.Order

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.orderDate)
        </dd>

        <dt>
            @Html.DisplayName("Total price")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalPrice)
        </dd>

        <dt>
            @Html.DisplayName("Order status")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.orderStatus)
        </dd>

        <dt>
            @Html.DisplayName("Login")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.client.clientLogin)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "IndexClient")
</p>

CCNetStore/Views/Orders/Edit.cshtml
@model CCNetStore.Models.Order

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Enter your delivery address</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.clientId)
    @Html.HiddenFor(model => model.orderDate)
    @Html.HiddenFor(model => model.totalPrice)
    @Html.HiddenFor(model => model.orderStatus)


    <div class="form-group">
        @Html.LabelFor(model => model.deliveryAddress, "Delivery address", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.deliveryAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.deliveryAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "IndexClient")
</div>

CCNetStore/Views/Orders/Index.cshtml
@model IEnumerable<CCNetStore.Models.Order>

@{
    ViewBag.Title = "Index";
}
<div class="col-md-2">
    <div class="btn-group-vertical btn-group-lg btn-block" role="group" aria-label="Menu" style="border:groove;">
        <h2 style="text-align:center">Menu</h2>
        <button type="button" class="btn btn-default" style="border-top:groove; border-bottom:none; border-right:none; border-left:none; border-radius: 0%;" onclick="location.href='@Url.Action("IndexManager", "Products")'">Catalog</button>
        <button type="button" class="btn btn-default" style="border:none; border-radius: 0%;" onclick="location.href='@Url.Action("Index", "Carts")'">Cart</button>
        <button type="button" class="btn btn-default" style="border:none; border-radius: 0%;" onclick="location.href='@Url.Action("Index", "Orders")'">Orders</button>
        @if (User.IsInRole("admin"))
        {
            <button type="button" class="btn btn-default" style="border:none; border-radius: 0%;" onclick="location.href='@Url.Action("Index", "Clients")'">Clients</button>
        }
    </div>
</div>
<div class="col-md-10" style="border:groove">
    <h2 style="text-align:center">* Orders *</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Client Id")
            </th>
            <th>
                @Html.DisplayName("Login")
            </th>
            <th>
                @Html.DisplayName("Date")
            </th>
            <th>
                @Html.DisplayName("Total price")
            </th>
            <th>
                @Html.DisplayName("Order status")
            </th>
            <th>
                @Html.DisplayName("Delivery address")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.clientId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.client.clientLogin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.orderDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.totalPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.orderStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.deliveryAddress)
                </td>
                <td>
                    @Html.ActionLink("Change delivery address", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>

CCNetStore/Views/Orders/IndexClient.cshtml
@model IEnumerable<CCNetStore.Models.Order>

@{
    ViewBag.Title = "IndexClient";
}
<div class="col-md-2">
    <div class="btn-group-vertical btn-group-lg btn-block" role="group" aria-label="Menu" style="border:groove;">
        <h2 style="text-align:center">Menu</h2>
        <button type="button" class="btn btn-default" style="border-top:groove; border-bottom:none; border-right:none; border-left:none; border-radius: 0%;" onclick="location.href='@Url.Action("IndexClient", "Products")'">Catalog</button>
        <button type="button" class="btn btn-default" style="border:none; border-radius: 0%;" onclick="location.href='@Url.Action("IndexClient", "Carts")'">Cart</button>
        <button type="button" class="btn btn-default" style="border:none; border-radius: 0%;" onclick="location.href='@Url.Action("IndexClient", "Orders")'">Orders</button>
    </div>
</div>
<div class="col-md-10" style="border:groove">
    <h2 style="text-align:center">* Orders @User.Identity.Name *</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Date")
            </th>
            <th>
                @Html.DisplayName("Total price")
            </th>
            <th>
                @Html.DisplayName("Order status")
            </th>
            <th>
                @Html.DisplayName("Delivery address")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.orderDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.totalPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.orderStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.deliveryAddress)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                    @if (item.deliveryAddress == null)
                    {
                        @Html.ActionLink("Add delivery address", "Edit", new { id = item.Id })
                    }
                    else
                    {
                        @Html.ActionLink("Pay", "PayForTheOrder", new { id = item.Id })
                    }
                </td>
            </tr>
        }

    </table>
</div>

CCNetStore/Views/Orders/PayForTheOrder.cshtml
@{
    ViewBag.Title = "PayForTheOrder";
}


    <h3>Order PAYED</h3>

    <div>
        <div class="col-md-offset-0 col-md-12">
            <h4>[@Html.ActionLink("Back to orders", "IndexClient")]</h4>
        </div>
    </div>